### ISSUE TITLE
latest version of node-fetch is not compatible with the types declared

### ISSUE THREAD

**Issue by Arditc** [commercetools/commercetools-sdk-typescript#213] opened 2022-03-04 17:40 UTC
I'm currently using the latest version of node fetch with the latest version of this SDK.
```
"@commercetools/sdk-client-v2": "^1.2.0",
"node-fetch": "^2.6.1"
```
The types are currently not compatible. Which version of node-fetch should I be using instead?

```
Argument of type '{ host: string; projectKey: string; credentials: { clientId: string; clientSecret: string; }; scopes: string[]; fetch: (url: RequestInfo, init?: RequestInit | undefined) => Promise<...>; }' is not assignable to parameter of type 'AuthMiddlewareOptions'.
  Types of property 'fetch' are incompatible.
    Type '(url: RequestInfo, init?: RequestInit | undefined) => Promise<Response>' is not assignable to type '(input: RequestInfo, init?: RequestInit | undefined) => Promise<Response>'.
      Types of parameters 'url' and 'input' are incompatible.
        Type 'RequestInfo' is not assignable to type 'import("/Users/X/repo/node_modules/node-fetch/@types/index").RequestInfo'.
          Type 'Request' is not assignable to type 'RequestInfo'.
            Type 'Request' is missing the following properties from type 'Request': size, bufferts(2345)

```

**Comment by ajimae** [comment] 2022-03-21 18:24
Hi @Arditc 

I have tried to reproduce this issue by creating a new project and using the latest version of `node-fetch`, the `@comemrcetools/sdk-client-v2` and also `@commercetools/platform-sdk` yet I couldn't seem to encounter this issue.

I think it will be nice if you can show us how to reproduce this on the this very version of node-fetch.

Cheers 🥂

**Comment by jimmythomson** [comment] 2022-03-21 20:30
Hi @ajimae  - I noticed this a few days ago too. I can replicate it by taking the example code in the sdk-client package README file, for example:

```
import {
    ClientBuilder,
    createAuthForClientCredentialsFlow,
    createHttpClient,
} from '@commercetools/sdk-client-v2'
import { createApiBuilderFromCtpClient }  from '@commercetools/platform-sdk'
import fetch from 'node-fetch'

const projectKey = 'mc-project-key'
const authMiddlewareOptions = {
    host: 'https://auth.europe-west1.gcp.commercetools.com',
    projectKey,
    credentials: {
        clientId: 'mc-client-id',
        clientSecret: 'mc-client-secrets',
    },
    oauthUri: '/oauth/token', // - optional: custom oauthUri
    scopes: [`manage_project:${projectKey}`],
    fetch,
}

const httpMiddlewareOptions = {
    host: 'https://api.europe-west1.gcp.commercetools.com',
    fetch,
}
const client = new ClientBuilder()
    .withProjectKey(projectKey)
    .withMiddleware(createAuthForClientCredentialsFlow(authMiddlewareOptions))
    .withMiddleware(createHttpClient(httpMiddlewareOptions))
    .withUserAgentMiddleware()
    .build()

// or
const client = new ClientBuilder()
    .withProjectKey(projectKey)
    .withClientCredentialsFlow(authMiddlewareOptions)
    .withHttpMiddleware(httpMiddlewareOptions)
    .withUserAgentMiddleware()
    .build()

const apiRoot = createApiBuilderFromCtpClient(client)
```

My `package.json` looks like this:

```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "tsc"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "typescript": "^4.5.5"
  },
  "dependencies": {
    "@commercetools/platform-sdk": "^2.5.0",
    "@commercetools/sdk-client-v2": "^1.2.0",
    "node-fetch": "^3.2.3"
  }
}
```

TypeScript gives me the exact same errors as described by @Arditc

**Comment by ajimae** [comment] 2022-03-22 13:26
Hi @jimmythomson 

Thanks for giving more details, I will look into this and find a fix for it.

Thanks

**Comment by ajimae** [comment] 2022-04-06 00:01
This should be fixed now. see [this](https://github.com/commercetools/commercetools-sdk-typescript/pull/239/files)

**Closed by ajimae** 2022-04-06 00:01 UTC
