### ISSUE TITLE
Fetching categories throws TypeError: this.requestExecutor is not a function

### ISSUE THREAD

**Issue by LesleyDuyndam** [commercetools/commercetools-sdk-typescript#132] opened 2021-10-25 13:58 UTC
Fetching categories (both single as lists) trough REST endpoints works as expected, making those same requests trough SDK seems to cause an issue where the requestExecutor is not a function. 

Other entities work as expected trough the SDK, so far we only encountered this behaviour on Category entities. The version of `@commercetools/platform-sdk` we are using is `^1.16.0`.

### Fetch category listing without filters
````
const apiRoot = createApiBuilderFromCtpClient(ctpClient);
const { body } = await apiRoot
  .withProjectKey({ projectKey })
  .categories()
  .get()
  .execute();

TypeError: this.requestExecutor is not a function
    at ApiRequest.execute (/Users/deity/Projects/falcon-platform/node_modules/@commercetools/platform-sdk/dist/commercetools-platform-sdk.cjs.dev.js:152:19)
````

### Fetch single category by Id
````
const apiRoot = createApiBuilderFromCtpClient(ctpClient);
const { body } = await apiRoot
  .withProjectKey({ projectKey })
  .categories()
  .withId({ ID })
  .get()
  .execute();

TypeError: this.requestExecutor is not a function
    at ApiRequest.execute (/Users/deity/Projects/falcon-platform/node_modules/@commercetools/platform-sdk/dist/commercetools-platform-sdk.cjs.dev.js:152:19)
````

**Comment by ajimae** [comment] 2021-11-02 11:49
Hi @LesleyDuyndam 

Sorry for the delayed response.

I tried reproducing this issue but I couldn't. I used both the latest version ("^1.19.0") of `@commercetools/platform-sdk` as well as version "^1.16.0".

I think the issue lies on which module was imported into your project. Whereas mine imported the production build module yours imported the dev version.

![Screen Shot 2021-11-02 at 12 41 01](https://user-images.githubusercontent.com/32770340/139839992-13db0248-4fbb-4ce9-846a-d92aa708f6b4.png)

Maybe you should check to see that the right `@commercetools/platform-sdk` was imported into your project.

Here is my test snippet.
```typescript
const { ClientBuilder, Client, HttpMiddlewareOptions, createAuthForClientCredentialsFlow, createHttpClient, AuthMiddlewareOptions } = require('@commercetools/sdk-client-v2')
const { ApiRoot, createApiBuilderFromCtpClient } = require('@commercetools/platform-sdk')
const fetch = require('node-fetch')

const projectKey = 'your-projectKey';

const authMiddlewareOptions = {
  host: 'https://auth.europe-west1.gcp.commercetools.com',
  projectKey,
  credentials: {
    clientId: process.env.CTP_CLIENT_ID || '',
    clientSecret: process.env.CTP_CLIENT_SECRET || '',
    // anonymousId: 'uniqueID'
  },
  oauthUri: process.env.adminAuthUrl || '',
  scopes: ['manage_project:your-projectKey'],
  fetch
}

const httpMiddlewareOptions = {
  host: 'https://api.europe-west1.gcp.commercetools.com',
  fetch,
}

const client = new ClientBuilder()
  .withProjectKey(projectKey)
  .withMiddleware(createAuthForClientCredentialsFlow(authMiddlewareOptions))
  .withMiddleware(createHttpClient(httpMiddlewareOptions))
  .withUserAgentMiddleware()
  .build()

const apiRoot = createApiBuilderFromCtpClient(client)

const getCategoryList = () => {
  return apiRoot
    .withProjectKey({ projectKey })
    .categories()
    .get()
    .execute();
}

getCategoryList()
  .then(console.log)
  .catch(console.error)

```

Please let me know if this was able to help you.

Thanks

**Comment by ashishhk** [comment] 2021-11-16 09:43
Closing this as the question was answered, let us know if you still have any other questions.

**Closed by ashishhk** 2021-11-16 09:43 UTC
Labels: Customer issue

**Comment by mickdekkers** [comment] 2024-03-25 16:18
In my case, this error was caused by having called `createApiBuilderFromCtpClient` with a `ctpClient` argument that's not a `Client`; I forgot to call `.build()` on the `ClientBuilder` and TypeScript didn't catch it because [the `ctpClient` argument is typed as `any`](https://github.com/commercetools/commercetools-sdk-typescript/blob/225ddc11b8642eae52a85fd8289f44636a043f46/packages/platform-sdk/src/ctp/ctp-client.ts#L4)

Version info:
`@commercetools/platform-sdk`: `7.1.0`
`@commercetools/sdk-client-v2`: `2.3.0`
