### ISSUE TITLE
Runtime error: Cannot find module 'buffer/'

### ISSUE THREAD

**Issue by sroibu** [commercetools/commercetools-sdk-typescript#413] opened 2023-01-23 11:12 UTC
Hi there,

After updating sdk-client from "@commercetools/sdk-client": "2.1.2" to "@commercetools/sdk-client-v2": "2.1.1" one of our lambda starts to fail with the following error:

```
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'buffer/'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'buffer/'",
        "Require stack:",
        "- /var/task/index.js",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1000:17)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1035:21)",
        "    at async start (file:///var/runtime/index.mjs:1200:23)",
        "    at async file:///var/runtime/index.mjs:1206:1"
    ]
}
```
It looks like the newer version has a very [specific import](https://github.com/commercetools/commercetools-sdk-typescript/blob/c605309ae63acb7d3a804c001c5680d63760fee6/packages/sdk-client/src/sdk-middleware-auth/build-requests.ts#L15) that tells nodejs to use the buffer implementation from node modules, however other tools like don't follow the same approach. 

We use esbuild to build our application and it treats the "buffer/" import as a native nodejs library and passes it out of the package. This results in a missing dependency at runtime :) 

Do you have any solutions how to overcome this problem?

**Comment by ajimae** [comment] 2023-01-23 12:38
Hi @sroibu

I believe this is because the bundler (jin this case the esbuild) is not properly resolving the `buffer` module to the polyfill provided.

I am not really familiar with `esbuild` but a quick look around shows we can resolve the `buffer` module to a specific installation just the way we did in our [webpack here](https://github.com/commercetools/commercetools-sdk-typescript/blob/5e70a433a5ba895fba01b65cf0add90e4b174556/webpack.config.js#L51).

Can you try and follow the instruction [here](https://github.com/cyco130/esbuild-plugin-polyfill-node) on how to do this.

I will also check to see if this has to do with a specific version of the `buffer` module, but in the mean time try resolving the module.


Thanks

**Comment by ajimae** [comment] 2023-02-20 09:14
Hi @sroibu 

Coming back to this issue.

You can take a look at how I was able to get this to work for `React` using `esbuild` and polyfiling the `process` and `buffer` modules.

Let us know if this helps.

Thanks

**Comment by ajimae** [comment] 2023-03-06 13:49
Closing this due to inactivity. Please feel free to reopen if you are still experiencing this issue.

Thanks

**Closed by ajimae** 2023-03-06 13:49 UTC
Labels: Customer issue

**Comment by Emanuele-Fortunati** [comment] 2023-11-23 18:49
@ajimae  I'm currently experiencing a very similar issue when I try to bundle with Rollup:

`'Buffer' is not exported by ../../node_modules/buffer/index.js, imported by ../../node_modules/@commercetools/sdk-client-v2/dist/commercetools-sdk-client-v2.esm.js`

It's a slightly different error message but the cause is the same. I've tried to get inspiration from your webpack and esbuild but on rollup I can't make it working. Any idea?

**Comment by ajimae** [comment] 2023-11-29 13:07
@Emanuele-Fortunati you have to polyfill the buffer module in rollup using the below code in your rollup config.

```js
import nodePolyfills from 'rollup-plugin-polyfill-node';
rollup({
  entry: 'main.js',
  plugins: [
    nodePolyfills({
      include: ["buffer", "stream", "events", ...],
    })
  ]
})
```

Reference: [Rollup polyfill package](https://www.npmjs.com/package/rollup-plugin-polyfill-node)

**Comment by Emanuele-Fortunati** [comment] 2023-11-29 14:01
@ajimae  you are a star! Thank you!
